### ISSUE TITLE
Allow multiple prisma clients

### ISSUE THREAD

**Issue by fedex995** [premieroctet/next-admin#120]
First of all, great work on making this next admin, works really good.

I was wondering if it's possible to handle more than one prisma client? Right now we have multiple prisma clients that connect to different dbs, and would be really nice to be able to spin up different next admins with these connections within the same next project (so /prisma-1 would use 1 connection + types and /prisma-2 would use another one and so on).

Is this something feasible?
Thanks in advance

**Comment by colin27091** [comment]
This is a good question, we've never used the library in this way. 
To try to reproduce this use case, we need to know how many `schema.prisma` do you have in your project, if only one, are you using [Prisma multiple schema](https://www.prisma.io/docs/orm/prisma-schema/data-model/multi-schema) or something else ? Next-admin massively uses JSON schema and Prisma namespace generated from `schema.prisma` to build forms and lists. 
Theoretically, the same pair [JSON schema - Prisma namespace] will produce the same admin (regardless of options). So, you let us curious about your case 

Thank you for your interest in our project

**Comment by fedex995** [comment]
We have 3 different schema.prisma pointing to different databases, so it's not the same db with different schemas (that case could be solved with the multiple schema option).
So in the end, we also have 3 different prisma clients, but the project is internally accessing the prisma client from '@prisma/client' for defining the NextAdminOptions types

**Comment by cregourd** [comment]
We've tried to reproduce your use case, unfortunately beyond the typing issues due to the `@prisma/client` type diff with other Prisma schemas, we ran into some other technical issues due to the `Prisma.dmmf` from `@prisma/client` being used to build the form, list and do modify the `json-schema`.

The current structure of next-admin can't handle these diffs as parameters. Also, in my opinion, you're facing an edge-case use of Prisma, I don't think we'll be making changes to support it, but if you want to, we'll be glad to review it

**Comment by fedex995** [comment]
Thanks for the response! I'll close the issue for now
