### ISSUE TITLE
Only using DataTable

### ISSUE THREAD

**Issue by MeshanKhosla** [premieroctet/next-admin#133]
Hi, thanks for this awesome library! 

Would it be possible to have an option to only export the data table so that it can be integrated with existing UIs a bit nicer? I'm interested in using this for an application that has an admin view as well as a normal view, but this would require the normal view to look identical to the styling of this library (ie: sidebar, logo, colors), and it would be amazing if we can directly place data tables in existing UIs.

**Comment by cregourd** [comment]
This library is intended to be a one-block turnkey tool for admin. If I understand your request well, you want next-admin to export the List component, unfortunately by doing this we can't ensure the well working of the component, also you will have to handle some logic currently handled by the lib due to your custom integration.
We recommend you to use a dedicated library to manage List, where you can go deeper into modularity.
