### ISSUE TITLE
[FEATURE] - Enable grouping of fields

### ISSUE THREAD

**Issue by malaney** [premieroctet/next-admin#356]
### Summary

Currently, the edit form for a given model displays one field per row.  In certain cases I'd like to display more than one field per row to enable a more compact form.  Would it be possible to allow grouping of fields within the edit form to achieve a layout similar to the below?

![image](https://github.com/premieroctet/next-admin/assets/517419/29957d07-dcf5-485f-b978-6fe5b9ea7c0a)

### Basic Example

Here is one example of what I'm trying to achieve:

![image](https://github.com/premieroctet/next-admin/assets/517419/13a491e1-8029-4f7b-9ab6-9b0bb0d42d8f)

### Drawbacks

I see no drawbacks to this proposal.

### Unresolved questions

I'm not aware of any unresolved questions.

**Comment by cregourd** [comment]
Hey @malaney 

The fix made in [v4.4.3](https://www.npmjs.com/package/@premieroctet/next-admin/v/4.4.3) was about a padding issue, since [v3.2.6](https://next-admin.js.org/changelog#326) you could customize your form using tailwind or custom classes.

The form is a `grid`, by using [grid-column](https://tailwindcss.com/docs/grid-column) and [grid-row](https://tailwindcss.com/docs/grid-row) you can move fields wherever you want

You can also change the form style by overriding the `_form` style, and change the number of columns

There is an example in demo code:
https://github.com/premieroctet/next-admin/blob/0bd0044d066c2acdf82a0c26af9cd103408817bb/apps/example/options.tsx#L82-L93

If you are still struggling, let us know 🚀

**Comment by malaney** [comment]
Hey @cregourd 

Thanks for the reply!  Unfortunately,  I am still having issues with the css for this form.  The form does not seem to respect the `_form: "grid-cols-2 gap-4 md:grid-cols-2"` style.  No matter what I do, I always seem to get a 3 column grid and not a 2 or a 4.  

Secondly, I am unable to get the `col-span-*` tag to work.  I am unable to get a form div to span more than one column.  This prevents me from being able to layout the `password` field in the picture above.  After each change I am deleting my `.next` directory and running `npm run dev` anew, so nothing is cached.  What is working is the `row-start-*` directive.  That does at least allow me to place elements in the rows that I want them in.

Thanks in advance for any advice you can provide,

Malaney

**Comment by cregourd** [comment]
There are two things you can do to fix this issue

If your `options` are defined in a separate file from your `page.js` don't forget to add that file to the content array of `tailwind.config.js`. In this way, tailwind won't forget to build the class names you use.

https://github.com/premieroctet/next-admin/blob/0bd0044d066c2acdf82a0c26af9cd103408817bb/apps/example/tailwind.config.js#L12

Secondly, I advise you to use the latest version of `next-admin`, as we have improved the merge class names system for the `_form` item 

Let us know if it helped 🚀

**Comment by cregourd** [comment]
Glad it worked out, we close this issue 🚀
