### ISSUE TITLE
Allow users to use a dev release of the library

### ISSUE THREAD

**Issue by tlenclos** [premieroctet/next-admin#61]
But I'm not sure how.

**Comment by cregourd** [comment]
According to the current size of the project, this feature doesn't seem very useful at the moment. However, we provide some information here for possible future implementation:

Using of `dev release` seems to be possible with `changeset` using [prerelease mode](https://github.com/changesets/changesets/blob/main/docs/prereleases.md). However, this mode seems to be broken with monorepo because it increases the dependency version of the updated package on all other dependent packages

We close this issue as `not-planned` 🚀
